---
title: "Reading"
citeproc: true
csl: apa-cv.csl
suppress-bibliography: true
toc: true
---

We have collected the following non-exhaustive list of articles about generative AI and education. 
There are grouped roughly by topic and ordered by first author.

Suggestions for additions welcomed at [https://github.com/beanumber/aalac2026/issues](https://github.com/beanumber/aalac2026/issues).

## AI and statistics education

1. @allabadi2025ai
1. @allabadi2025enhancing
1. @dunn2025generative
1. @ellis2023new
1. @furfaro2026
1. @hoerl2025future
1. @schwarz2025use
1. @vilakati2026harnessing
1. @xie2025comparing
1. @xing2024exploring

## AI and data science education

1. @avila2025curriculum
1. @bien2025generative
1. @bray2025tutorial
1. @cui2026same
1. @doleck2025generative
1. @hao2025research
1. @hageman2025
1. @irvine2023opportunities
1. @jeon2024staged
1. @valverde2024advanced
1. @wilke2025teaching

## AI and programming education

1. @daniotti2026using
1. @lepp2025does
1. @dasilva2024chatgpt

## AI and statistical writing

1. @deluca2025developing
1. @reinhart2025llms

## AI and computer science education

1. @barr2025
1. @sarkar2024obey
1. @shein2024
1. @smith2024early

## AI and the humanities / K-12 / general education

1. @barcelona2025development
1. @beers20102009
1. @darvishi2024impact
1. @drozda2026
1. @eriksen2026prompt
1. @fernandes2025ai
1. @klein2025provocations
1. @koebler2025teachers
1. @lehmann2025
1. @luckin2024double
1. @neumann2023we
1. @oberlinluddite2025luddite
1. @sarat2026
1. @shirky2025students
1. @singer2025welcome
1. @stanford2023
1. @walsh2025everyone


## AI and science education

1. @cooper2023examining
1. @ferguson2025researcher

## AI and data science ethics

1. @science2026aiagents
1. @lewis2022teaching
1. @stoyanovich2022teaching

## AI and mathematics education

1. @avendano2024impacto
1. @trindade2025teaching
1. @wardat2023chatgpt

## AI and engineering education

1. @bravo2024engineering
1. @erez2025how

## Teaching neural networks

1. @tian2025practice

## AI and research

1. @runge2025

Last updated July 12, 2026
