---
title: "Schedule"
---


```{r}
#| message: false
#| echo: false
classes <- c(
  as.Date("2026-07-19") + lubridate::ddays(0:4)
) |>
  sort()

i <- 0
echo_date <- function(...) {
  i <<- i + 1
  x <- classes[i] |>
    format("%a, %b %e")
  htmltools::div(
    class = "card-header",
    "data-date" = classes[i],
    htmltools::h4(paste(i, ".", x, ...))
  )
}

topic <- function() {
  paste(fontawesome::fa("lightbulb"), "Topic:")
}
slides <- function() {
  paste(fontawesome::fa("microphone"), "Speaker:")
}
discuss <- function() {
  paste(fontawesome::fa("comment"), "Discussion:")
}
eat <- function() {
  paste(fontawesome::fa("utensils"), "Meal:")
}
```

::: {.grid}

::: {.g-col-6 .card} 
`r echo_date(emoji::emoji("train"))`

::: {.callout-important title="Theme: What's going on?"} 
- Lead: Manolis
:::

- \[4:00-4:45\]: Arrival and registration (PAC, Frank Center for Public Affairs Forum)
    - Location: Frank PAC forum #101
- \[4:45-5:00\]: Welcome from Nicole Stanton (Provost and Senior Vice-President for Academic Affairs)
    - Location: Frank PAC forum #101
- \[5:00-6:15\]: Plenary Session  
    - `r slides()` Alex Reinhart (Carnegie Mellon University): "The role of AI in statistics and data science education"
    - Location: Frank PAC forum #101
- \[7:00-8:30\]: Dinner
    - `r eat()` Dinner at the Armory
    - Location: Middletown Inn

::: {.callout-note title="Homework"} 

- **Skim** the GAISE College report:
    - @carver2016guidelines
    - @2025guidelines [link](https://asacollegegaise.org)

:::

::: 
::: {.g-col-6 .card} 
`r echo_date(emoji::emoji("list"))`

::: {.callout-important title="Theme: What we teach"} 
- Lead: Nick
:::

- \[7:30-8:30\]:   
    - `r eat()` Breakfast  
    - Location: Hotel
- \[9:00-10:15\]:	Session 1
    - `r topic()` Overview of the GAISE principles and recent data and computing initiatives
    - `r slides()` Nick Horton  
    - Location: Allbritton #103
- \[10:45-12:00\]: Session 2
    - `r topic()` AI and data analysis (lightning talks by Sorelle Friedler, Marc Schulz, and Stephen Freund)
    - Location: Allbritton #103
- \[12:10-1:30\]:   
    - `r eat()` Lunch  
    - Location: Allbritton #311
- \[1:45-3:00\]: Session 3
    - `r topic()` AI and the GAISE principles 
    - `r discuss()` in 3 groups
    - Location: Allbritton #004, #103, and #304
- \[3:30-4:45\]: Session 4
    - `r topic()` How might we update the GAISE College guidelines in an AI age?  
    - `r discuss()` plenary
    - Location: Allbritton #311
- \[6:30-8:00\] Dinner  
    - `r eat()` [Esca](https://escact.com/)  
    - Location:  
    [Esca Restaurant & Wine Bar](https://www.google.com/maps/place/Esca+Restaurant+%26+Wine+Bar/@41.5621325,-72.6511528,17z/data=!3m1!5s0x89e64a5b370f1229:0xf0a9528b913bdbca!4m14!1m7!3m6!1s0x89e64a5b37abd481:0x34233e86ed54db3b!2sEsca+Restaurant+%26+Wine+Bar!8m2!3d41.5621325!4d-72.6511528!16s%2Fg%2F1tgxk1zp!3m5!1s0x89e64a5b37abd481:0x34233e86ed54db3b!8m2!3d41.5621325!4d-72.6511528!16s%2Fg%2F1tgxk1zp?entry=ttu&g_ep=EgoyMDI2MDYxMC4wIKXMDSoASAFQAw%3D%3D)  
    437 Main St  
    Middletown, CT 06457



::: {.callout-note title="Homework"}

:::

:::



::: {.g-col-6 .card} 
`r echo_date(emoji::emoji("student"))`


::: {.callout-important title="Theme: How we teach"} 
- Lead: Sarah
:::

- \[7:30-8:30\]:
    - `r eat()` Breakfast  
    - Location: Hotel
- \[9:00-10:15\]:	Session 5
    - `r topic()` What we know about how students are using AI and student attitudes toward AI (lightning talks by Rachel Barlow, Casey Pattanayak, Zhe Wang, and Alex Reinhart)
    - Location: Allbritton #103
- \[10:45-12:00\]: Session 6 
    - `r topic()` Impact of AI on student learning
    - Location: Allbritton #103
- \[12:10-1:30\]:   
    - `r eat()` Lunch  
    - Location: Allbritton #311
- \[1:45-3:15\]: Session 7
    - `r topic()` Develop activities that use AI to accomplish learning goals, as tutor, and/or productivity tools
    - `r discuss()` in 3 groups
    - Location: Allbritton #004, #103, and #304

- \[3:15-6:45\]: Free time: Optional walk/hike at [Wadsworth falls park](https://ctparks.com/parks/wadsworth-falls-state-park). (No need for hiking boots, just walking shoes.)
- \[6:45-8:00\] Dinner  
    - `r eat()` [Tate's](https://www.tatesmiddletown.com/menu)  
    - Location:  
    [Tate's](https://www.google.com/maps/place/Tate's/@41.5601175,-72.6474524,17z/data=!3m1!4b1!4m6!3m5!1s0x89e64b8624f9a053:0xcc30d892f03d5ed6!8m2!3d41.5601135!4d-72.6448775!16s%2Fg%2F11y44y87bt?entry=ttu&g_ep=EgoyMDI2MDYxMC4wIKXMDSoASAFQAw%3D%3D)  
    80 Harbor Dr  
    Middletown, CT 06457


::: {.callout-note title="Homework"}

:::


:::
::: {.g-col-6 .card} 
`r echo_date(emoji::emoji("suitcase"))`

::: {.callout-important title="Theme: What comes next?"} 
- Lead: Ben
:::

- \[7:30-8:30\]:   
    - `r eat()` Breakfast  
    - Location: Hotel
- \[9:00-10:15\]:	Session 9 
    - `r fontawesome::fa("pencil")`: Collaborative writing
    - Location: Allbritton #311 (and #004, #113, and #304 as needed)
- \[10:45-12:00\]: Session 10  
    - `r fontawesome::fa("pencil")`: Collaborative writing
    - Location: Allbritton #311 (and #004, #113, and #304 as needed)
- \[12:00-1:00\]:   
    - `r eat()` Boxed lunch  
- \[1:00\]: Departures   




:::


:::

Last updated July 11, 2026
